#!/bin/bash
echo ""
echo "Do you want to install Honeygrove to the current directory?"
while true; do
    read  yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done

pwd > ~/.honeygrove_install
install_path=$(pwd)

echo ""
echo "Do you want to install Broker?"
while true; do
    read yn
    case $yn in
        [Yy]* ) install_broker=true; break;;
        [Nn]* ) install_broker=false; break;;
        * ) echo "Please answer yes or no.";;
    esac
done

if $install_broker; then
	cd /tmp/
	mkdir broker
	cd broker
	sudo apt-get -y install build-essential cmake curl git librocksdb-dev python python-dev python-pip swig git curl python3-pip
	sudo curl -LO https://github.com/actor-framework/actor-framework/archive/0.14.5.tar.gz
	tar -xzf 0.14.5.tar.gz
	cd actor-framework-0.14.5
	sudo ./configure
	sudo make -j4 install
	cd ..
	git clone --recursive  https://github.com/bro/broker ./broker-git
	cd broker-git
	git checkout topic/mfischer/broker-multihop
	sudo git submodule update
	git checkout master -- bindings/python/CMakeLists.txt
	git checkout master -- bindings/python/pybroker.i
	sudo echo -e "set(Python_ADDITIONAL_VERSIONS 3)\n$(cat bindings/python/CMakeLists.txt)" > bindings/python/CMakeLists.txt
	cd cmake/
	git checkout master -- FindPythonDev.cmake
	cd ..
	sudo ./configure
	sudo make -j4 install
	cd ../..
	sudo rm -rf broker
	echo "=== Broker Installation finished ==="
fi

sudo pip3 install -U Twisted
sudo pip3 install -U cryptography

echo "=== Python Dependencies satisfied ==="
echo ""
echo "Make link to /usr/local/bin?"
while true; do
    read  yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done


cd /usr/local/bin
sudo ln -s "$install_path"/honeygrove.sh honeygrove
