#!/bin/bash
echo ""
echo "Do you want to install Honeygrove to the current directory?"
while true; do
    read  yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done

pwd > ~/.honeygrove_install
install_path=$(pwd)

echo ""
echo "Do you want to install Broker?"
while true; do
    read yn
    case $yn in
        [Yy]* ) install_broker=true; break;;
        [Nn]* ) install_broker=false; echo "Remember to adjust your configuration accordingly in config.py"; break;;
        * ) echo "Please answer yes or no.";;
    esac
done

sudo apt-get install build-essential libssl-dev libffi-dev python-dev

if $install_broker; then
	cd /tmp/
	mkdir broker
	cd broker
	git clone --recursive https://github.com/bro/broker ./broker-git --branch v1.0.1 
	cd broker-git
	./configure --with-python=/usr/bin/python3
	make -j4 
	sudo make install
	cd ../..
	rm -rf broker
	echo "=== Broker Installation finished ==="
fi

sudo pip3 install -U Twisted
sudo pip3 install -U cryptography
sudo pip3 install -U pyopenssl

echo "=== Python Dependencies satisfied ==="
echo ""
echo "Make link to /usr/local/bin?"
while true; do
    read  yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done


cd /usr/local/bin
sudo ln -s "$install_path"/honeygrove.sh honeygrove
